### PR TITLE
#160583958 users should be able to signup

### PR DESCRIPTION
**Pull request by Edward-K1**
#### What does this PR do?
It enables users to create accounts on our web application
#### Description of Task to be completed?

- Create user input  form
- Validate details and provide descriptive error messages
- Store valid user details
- Send verification link to email

#### How should this be manually tested?

- Checkout into the branch
- Run `yarn install` then `yarn start`
- Click on the `get started` button to navigate to the signup route
- Provide valid details to register successfully

#### What are the relevant pivotal tracker stories?
[#160583958](https://www.pivotaltracker.com/story/show/160583958)
#### Screenshots (if appropriate)
image

### CODE REVIEW

**Comment by balaakagordon** [comment]
LGTM

**Comment by balaakagordon** [comment]
This is great work, Edward! My only request is to move the signup form a little lower on the screen.

**Comment by nakimera** [comment]
Good work Edward. I agree with Gordon. Would you please center the form in the middle of the page

**Comment by Edward-K1** [comment]
@nakimera , @balaakagordon , done.

**Comment by nakimera** [comment]
LGTM

**Comment by balaakagordon** [comment]
Thanks for making the changes. LGTM

**Comment by kenneth051** [comment]
LGTM

**Pull request merged**
