### PR TITLE
#161929905 User should be able to navigate the application

### PR DESCRIPTION
**Pull request by nakimera**
####  What does this PR do?
This PR adds a navigation bar to the application

####  Description of the task to be completed
Users should have a roadmap to effortlessly navigate the application

####  How should this be manually tested?
- Clone this branch

`git clone origin ft-navigation-bar-161929905`

- Start server

`yarn start`

- Log into your Authors Haven account 

#### Screenshots

The navigation bar on the landing page

screen shot 2018-11-15 at 09 46 30

The navigation bar after logging in

screen shot 2018-11-15 at 09 46 52

#### Relevant pivotal tracker story
[#161929905](https://www.pivotaltracker.com/n/projects/2198584/stories/161929905)

### CODE REVIEW

**Comment by Edward-K1** [comment]
Good work on the navigation bar @nakimera, however, I noticed some color inconsistency between the tags, search bar, and buttons (black, chocolate brown and a light-brownish color)

**Comment by balaakagordon** [comment]
LGTM

**Comment by nakimera** [comment]
@Edward-K1 Thanks for the feedback. I have made the changes

**Comment by j0flintking02** [comment]
LGTM

**Comment by Edward-K1** [comment]
LGTM.

**Pull request merged**
