### PR TITLE
#160583970 Users should be able to follow each other

### PR DESCRIPTION
**Pull request by balaakagordon**
#### What does this PR do?
Enables users to follow each other
#### Description of Task to be completed?
Have the following endpoints working
- `POST: profile/<str:username>/follow/`
- `DELETE: profile/<str:username>/unfollow/`
- `GET: profile/<str:username>/followers/`
- `GET: profile/<str:username>/following/`
#### How should this be manually tested?
After pulling this branch locally,
- run `yarn install` to install all dependencies
- run `yarn start` to start the application in the browser
- Click `Get Started` and create a user using the signup form
- Create another user and login to Author's Haven
- Click on your username in the Navigation bar and select "Authors"
- Find the user you created and click on the username
- Click the `Follow` button and watch the page update. Then click `Unfollow`
#### What are the relevant pivotal tracker stories?
[#160583970](https://www.pivotaltracker.com/story/show/160583970)
#### Screenshots (if appropriate)

### CODE REVIEW

**Comment by nakimera** [comment]
LGTM

**Comment by kenneth051** [comment]
LGTM

**Review by kenneth051 — CHANGES_REQUESTED** [review]
Nice work Gordon. However, the tests seem to be failing.Can you kindly fix them.

**Review by kenneth051 — APPROVED** [review]

**Comment by kenneth051** [comment]
LGTM

**Pull request merged**
