### PR TITLE
chore #160583956 Setup SASS processing

### PR DESCRIPTION
**Pull request by kenneth051**
**What does this PR do?**
Setup SASS processing on the client

**Description of Task to be completed**
Currently, the application lets us use only files with the  .css extension for styling. With this task,
 SASS enable the use of both .scss and .css files on the client.

**How should this be tested manually**
- Run `npm install` to install all dependencies
 - Run `npm start ` to see that the app still works fine 

**Relevant Pivotal Tracker Stories**

[#160583956](https://www.pivotaltracker.com/n/projects/2198584/stories/160583956)

#### Any background context you want to add?
N/A

**Screenshots**

screen shot 2018-11-01 at 10 03 23
screen shot 2018-11-01 at 10 03 46

### CODE REVIEW

**Review by Edward-K1 — APPROVED** [review]
LGTM.

**Review by balaakagordon — APPROVED** [review]
Looks ok

**Review by j0flintking02 — APPROVED** [review]
LGTM

**Comment by nakimera** [comment]
LGTM

**Review by lym — COMMENTED** [review]
LGTM

**Pull request merged**
