### PR TITLE
#160583957 add code climate coverage test after passing the tests from circleci

### PR DESCRIPTION
**Pull request by j0flintking02**
#### What does this PR do?
Add code climate coverage badge
##### Code coverage
This helps whoever is contributing to the project to understand the status of the project that is to say how much code is covered in the tests 
##### Code climate 
This helps who ever is contributing to the project to see the quality of code that he/she is writing against to what is already there
#### Screen Shots
screen shot 2018-11-01 at 15 37 54

#### Link to the relevant Pivotal stories
[#160583957](https://www.pivotaltracker.com/n/projects/2198584/stories/160583957)

### CODE REVIEW

**Review by kenneth051 — DISMISSED** [review]
Good job Jonathan, this is good. However, we all need to add a new line at the end of our last code lines in every file so that git doesn't flag it red.

**Review by balaakagordon — APPROVED** [review]
Great work! Don't forget the blank line at the end of your files

**Comment by kenneth051** [comment]
LGTM

**Review by Edward-K1 — APPROVED** [review]

**Comment by nakimera** [comment]
LGTM

**Pull request merged**
