### PR TITLE
#160583963  Users should create articles 

### PR DESCRIPTION
**Pull request by kenneth051**
**What does this PR do?**
Enables users to create articles.

**Description of task to be completed**
Articles form the backbone of our application. This task enables users to create and view the contents of an article. Only authenticated users can create articles.

**How should this be manually tested?**
Clone the repository, checkout into this branch
- Run `npm install` to install all dependencies
- Run  `npm test` to run the tests
- Run `npm start`

**Relevant Pivotal Tracker Stories**

[#160583963](https://www.pivotaltracker.com/n/projects/2198584/stories/160583963)

#### Any background context you want to add?
N/A

**Screen shots**

screen shot 2018-11-12 at 12 47 32

screen shot 2018-11-12 at 12 48 13

screen shot 2018-11-15 at 11 48 17

### CODE REVIEW

**Review by balaakagordon — APPROVED** [review]
LGTM

**Comment by Edward-K1** [comment]
Good work @kenneth051 , but please improve the display of the fetched articles.

**Review by j0flintking02 — APPROVED** [review]
LGTM

**Comment by nakimera** [comment]
LGTM

**Pull request merged**
